sudo: required
services:
  - docker

before_install:
  - docker build -t johanwikman/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true johanwikman/udemy-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "udemy-docker-react"
  env: "UdemyDockerReact-Prod"
  bucket_name: "elasticbeanstalk-us-west-2-030149269678"
  bucker_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY    
